name = "only-api"
main = "apps/api/src/index.ts"
compatibility_date = "2026-07-13"
workers_dev = true
keep_vars = true

[vars]
WORKERS_DAILY_REQUEST_LIMIT = "100000"

[triggers]
crons = ["0 * * * *"]

[observability]
enabled = true
